In [1]:
import pandas as pd

In [3]:
# Read CSV (header is kept as usual)
df = pd.read_csv("swtcp_mnist_iid_40pct_magz3_free_rider_client_list.csv")

# First column (A) and second column (B), starting from Excel row 2
col_a = df.iloc[:, 0]
col_b = df.iloc[:, 1]

# Create lists
fr2_list = col_b[col_a == "FR2"].tolist()
fr3_list = col_b[col_a == "FR3"].tolist()

print("FR2:", fr2_list)
print("FR2:", len(fr2_list))
print("FR3:", fr3_list)
print("FR3:", len(fr3_list))

FR2: [0, 3, 4, 5, 6, 11, 13, 14, 17, 19, 20, 24, 25, 27, 28, 29, 31, 35, 43, 53, 54, 57, 64, 67, 69, 71, 75, 77, 79, 81, 82, 84, 86, 88, 89, 90, 93, 94, 95, 97]
FR2: 40
FR3: [0, 3, 4, 5, 6, 11, 13, 14, 17, 19, 20, 24, 25, 27, 28, 29, 31, 35, 43, 53, 54, 57, 64, 67, 69, 71, 75, 77, 79, 81, 82, 84, 86, 88, 89, 90, 93, 94, 95, 97]
FR3: 40

In [4]:
# Read the CSV
df = pd.read_csv("swtcp_mnist_iid_fr2_fr3_40pct_magz3_cosine_matrix_by_round.csv")

# Excel rows 2-41 (40 rows)
data = df.iloc[0:40]

# Column B (2nd column)
rounds = data.iloc[:, 1].tolist()

# Columns E:CZ (5th to 104th columns)
cosine_values = data.iloc[:, 4:104]

print(rounds)
print(cosine_values)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
                  client_0               client_1              client_2  \
0                      NaN                    NaN                   NaN
1                      NaN                    NaN                   NaN
2                      NaN                    NaN                   NaN
3                      NaN                    NaN                   NaN
4                      NaN                    NaN                   NaN
5                      NaN                    NaN                   NaN
6                      NaN                    NaN                   NaN
7                      NaN                    NaN                   NaN
8                      NaN                    NaN                   NaN
9                      NaN                    NaN                   NaN
10   cos=0.7507\nz=95.1764                    NaN                   NaN
11                     NaN  cos=-0.0038\nz=0.6554                   NaN
12                     NaN                    NaN                   NaN
13                     NaN                    NaN                   NaN
14                     NaN                    NaN  cos=0.0165\nz=0.0746
15                     NaN                    NaN                   NaN
16                     NaN                    NaN                   NaN
17                     NaN                    NaN                   NaN
18                     NaN                    NaN                   NaN
19                     NaN                    NaN                   NaN
20                     NaN                    NaN                   NaN
21                     NaN                    NaN  cos=0.5803\nz=0.2995
22                     NaN                    NaN                   NaN
23                     NaN                    NaN                   NaN
24                     NaN                    NaN                   NaN
25                     NaN                    NaN                   NaN
26  cos=-0.0096\nz=52.5955                    NaN                   NaN
27                     NaN   cos=0.4658\nz=0.4994                   NaN
28                     NaN                    NaN                   NaN
29                     NaN                    NaN                   NaN
30                     NaN                    NaN                   NaN
31                     NaN                    NaN                   NaN
32                     NaN                    NaN                   NaN
33                     NaN                    NaN  cos=0.8307\nz=0.3484
34                     NaN                    NaN                   NaN
35                     NaN                    NaN                   NaN
36  cos=-0.0117\nz=48.8615                    NaN                   NaN
37                     NaN                    NaN                   NaN
38                     NaN                    NaN                   NaN
39                     NaN  cos=-0.0126\nz=0.8276                   NaN

                  client_3                client_4                client_5  \
0                      NaN                     NaN                     NaN
1                      NaN                     NaN                     NaN
2                      NaN                     NaN                     NaN
3                      NaN                     NaN                     NaN
4                      NaN                     NaN                     NaN
5                      NaN                     NaN                     NaN
6                      NaN                     NaN                     NaN
7                      NaN                     NaN                     NaN
8                      NaN                     NaN                     NaN
9                      NaN                     NaN                     NaN
10                     NaN                     NaN                     NaN
11                     NaN                     NaN                     NaN
12                     NaN                     NaN                     NaN
13                     NaN                     NaN                     NaN
14   cos=0.5198\nz=47.4764   cos=0.5175\nz=47.3428                     NaN
15                     NaN                     NaN                     NaN
16                     NaN                     NaN                     NaN
17                     NaN                     NaN                     NaN
18                     NaN                     NaN                     NaN
19                     NaN                     NaN   cos=0.5796\nz=51.1606
20  cos=-0.0091\nz=41.2593                     NaN                     NaN
21                     NaN                     NaN                     NaN
22                     NaN                     NaN                     NaN
23                     NaN                     NaN                     NaN
24                     NaN                     NaN                     NaN
25                     NaN                     NaN                     NaN
26                     NaN                     NaN  cos=-0.0187\nz=52.6317
27                     NaN                     NaN                     NaN
28                     NaN  cos=-0.0051\nz=53.4754                     NaN
29                     NaN                     NaN                     NaN
30                     NaN                     NaN                     NaN
31                     NaN                     NaN                     NaN
32                     NaN                     NaN  cos=-0.0139\nz=49.8432
33                     NaN                     NaN                     NaN
34                     NaN  cos=-0.0067\nz=55.5808                     NaN
35                     NaN                     NaN                     NaN
36  cos=-0.0059\nz=48.9016                     NaN                     NaN
37                     NaN                     NaN                     NaN
38                     NaN                     NaN                     NaN
39                     NaN                     NaN                     NaN

                  client_6              client_7              client_8  \
0                      NaN                   NaN                   NaN
1                      NaN                   NaN                   NaN
2                      NaN                   NaN                   NaN
3                      NaN                   NaN                   NaN
4                      NaN                   NaN                   NaN
5                      NaN                   NaN                   NaN
6                      NaN                   NaN                   NaN
7                      NaN                   NaN                   NaN
8                      NaN                   NaN                   NaN
9                      NaN                   NaN                   NaN
10   cos=0.7529\nz=94.9875                   NaN                   NaN
11                     NaN                   NaN                   NaN
12                     NaN  cos=0.0080\nz=0.4435                   NaN
13                     NaN                   NaN                   NaN
14                     NaN                   NaN                   NaN
15                     NaN                   NaN                   NaN
16                     NaN                   NaN                   NaN
17                     NaN                   NaN                   NaN
18                     NaN                   NaN  cos=0.0087\nz=0.1304
19                     NaN                   NaN                   NaN
20                     NaN                   NaN                   NaN
21                     NaN                   NaN                   NaN
22                     NaN                   NaN                   NaN
23                     NaN                   NaN                   NaN
24                     NaN                   NaN                   NaN
25                     NaN                   NaN  cos=0.2919\nz=0.1706
26                     NaN                   NaN                   NaN
27                     NaN                   NaN                   NaN
28  cos=-0.0029\nz=53.3823                   NaN                   NaN
29                     NaN                   NaN                   NaN
30                     NaN                   NaN                   NaN
31                     NaN  cos=0.4263\nz=0.2937                   NaN
32  cos=-0.0047\nz=49.7263                   NaN                   NaN
33                     NaN                   NaN                   NaN
34                     NaN                   NaN                   NaN
35                     NaN  cos=0.3342\nz=0.3023                   NaN
36                     NaN                   NaN                   NaN
37                     NaN                   NaN                   NaN
38                     NaN                   NaN                   NaN
39                     NaN                   NaN  cos=0.4752\nz=0.0373

                client_9  ...              client_90              client_91  \
0                    NaN  ...                    NaN                    NaN
1                    NaN  ...                    NaN                    NaN
2                    NaN  ...                    NaN                    NaN
3                    NaN  ...                    NaN                    NaN
4                    NaN  ...                    NaN                    NaN
5                    NaN  ...                    NaN                    NaN
6                    NaN  ...                    NaN                    NaN
7                    NaN  ...                    NaN                    NaN
8                    NaN  ...                    NaN                    NaN
9                    NaN  ...                    NaN                    NaN
10                   NaN  ...                    NaN  cos=-0.0003\nz=0.1322
11                   NaN  ...                    NaN                    NaN
12                   NaN  ...                    NaN                    NaN
13                   NaN  ...                    NaN                    NaN
14                   NaN  ...                    NaN                    NaN
15                   NaN  ...                    NaN                    NaN
16  cos=0.0243\nz=0.2763  ...  cos=0.7086\nz=44.3675                    NaN
17                   NaN  ...                    NaN                    NaN
18                   NaN  ...                    NaN                    NaN
19                   NaN  ...                    NaN                    NaN
20                   NaN  ...                    NaN                    NaN
21                   NaN  ...                    NaN                    NaN
22                   NaN  ...                    NaN                    NaN
23                   NaN  ...                    NaN                    NaN
24                   NaN  ...                    NaN                    NaN
25                   NaN  ...                    NaN                    NaN
26                   NaN  ...                    NaN                    NaN
27  cos=0.6790\nz=0.1441  ...                    NaN                    NaN
28                   NaN  ...  cos=0.0046\nz=53.2901                    NaN
29                   NaN  ...                    NaN                    NaN
30                   NaN  ...                    NaN                    NaN
31                   NaN  ...                    NaN   cos=0.6519\nz=0.0048
32                   NaN  ...                    NaN                    NaN
33                   NaN  ...                    NaN                    NaN
34                   NaN  ...                    NaN                    NaN
35                   NaN  ...                    NaN                    NaN
36                   NaN  ...                    NaN                    NaN
37                   NaN  ...                    NaN                    NaN
38                   NaN  ...                    NaN                    NaN
39                   NaN  ...                    NaN                    NaN

               client_92               client_93               client_94  \
0                    NaN                     NaN                     NaN
1                    NaN                     NaN                     NaN
2                    NaN                     NaN                     NaN
3                    NaN                     NaN                     NaN
4                    NaN                     NaN                     NaN
5                    NaN                     NaN                     NaN
6                    NaN                     NaN                     NaN
7                    NaN                     NaN                     NaN
8                    NaN                     NaN                     NaN
9                    NaN                     NaN                     NaN
10                   NaN                     NaN                     NaN
11                   NaN                     NaN                     NaN
12                   NaN                     NaN                     NaN
13                   NaN                     NaN                     NaN
14                   NaN                     NaN                     NaN
15                   NaN                     NaN                     NaN
16                   NaN                     NaN                     NaN
17  cos=0.0101\nz=0.0265                     NaN   cos=0.4130\nz=47.2395
18                   NaN                     NaN                     NaN
19                   NaN   cos=0.5802\nz=51.2007                     NaN
20                   NaN                     NaN                     NaN
21                   NaN                     NaN                     NaN
22                   NaN                     NaN                     NaN
23  cos=0.7450\nz=0.2212                     NaN                     NaN
24                   NaN                     NaN  cos=-0.0123\nz=47.1392
25                   NaN                     NaN                     NaN
26                   NaN                     NaN                     NaN
27                   NaN                     NaN                     NaN
28                   NaN                     NaN                     NaN
29                   NaN                     NaN                     NaN
30                   NaN  cos=-0.0171\nz=48.3928                     NaN
31                   NaN                     NaN                     NaN
32                   NaN                     NaN                     NaN
33                   NaN                     NaN                     NaN
34                   NaN                     NaN                     NaN
35  cos=0.5640\nz=0.1861                     NaN                     NaN
36                   NaN                     NaN                     NaN
37                   NaN                     NaN                     NaN
38                   NaN                     NaN                     NaN
39                   NaN                     NaN                     NaN

                 client_95             client_96               client_97  \
0                      NaN                   NaN                     NaN
1                      NaN                   NaN                     NaN
2                      NaN                   NaN                     NaN
3                      NaN                   NaN                     NaN
4                      NaN                   NaN                     NaN
5                      NaN                   NaN                     NaN
6                      NaN                   NaN                     NaN
7                      NaN                   NaN                     NaN
8                      NaN                   NaN                     NaN
9                      NaN                   NaN                     NaN
10                     NaN                   NaN                     NaN
11   cos=0.7283\nz=74.5612  cos=0.0240\nz=0.0386                     NaN
12                     NaN                   NaN                     NaN
13                     NaN                   NaN                     NaN
14                     NaN                   NaN                     NaN
15                     NaN                   NaN   cos=0.3931\nz=41.8768
16                     NaN                   NaN                     NaN
17                     NaN                   NaN                     NaN
18                     NaN                   NaN                     NaN
19                     NaN                   NaN                     NaN
20  cos=-0.0161\nz=41.3539                   NaN                     NaN
21                     NaN                   NaN                     NaN
22                     NaN                   NaN                     NaN
23                     NaN                   NaN                     NaN
24                     NaN                   NaN                     NaN
25                     NaN                   NaN                     NaN
26                     NaN                   NaN  cos=-0.0052\nz=52.6386
27                     NaN  cos=0.5109\nz=0.0036                     NaN
28                     NaN                   NaN                     NaN
29                     NaN                   NaN                     NaN
30                     NaN                   NaN                     NaN
31                     NaN                   NaN                     NaN
32                     NaN                   NaN  cos=-0.0129\nz=49.8253
33                     NaN  cos=0.2872\nz=0.2544                     NaN
34  cos=-0.0052\nz=55.5447                   NaN                     NaN
35                     NaN                   NaN                     NaN
36                     NaN                   NaN                     NaN
37                     NaN                   NaN                     NaN
38                     NaN                   NaN                     NaN
39                     NaN                   NaN                     NaN

               client_98             client_99
0                    NaN                   NaN
1                    NaN                   NaN
2                    NaN                   NaN
3                    NaN                   NaN
4                    NaN                   NaN
5                    NaN                   NaN
6                    NaN                   NaN
7                    NaN                   NaN
8                    NaN                   NaN
9                    NaN                   NaN
10                   NaN                   NaN
11                   NaN                   NaN
12                   NaN                   NaN
13                   NaN                   NaN
14                   NaN                   NaN
15                   NaN                   NaN
16  cos=0.0037\nz=0.0662                   NaN
17                   NaN  cos=0.0072\nz=0.1158
18                   NaN                   NaN
19                   NaN                   NaN
20                   NaN                   NaN
21                   NaN                   NaN
22                   NaN                   NaN
23                   NaN                   NaN
24                   NaN                   NaN
25                   NaN                   NaN
26                   NaN                   NaN
27                   NaN                   NaN
28                   NaN                   NaN
29                   NaN  cos=0.4693\nz=0.0134
30                   NaN                   NaN
31  cos=0.2910\nz=0.6390                   NaN
32                   NaN                   NaN
33                   NaN                   NaN
34                   NaN                   NaN
35                   NaN  cos=0.7682\nz=0.2831

In [7]:
import pandas as pd
import numpy as np

# Read CSV
df = pd.read_csv("swtcp_mnist_iid_fr2_fr3_40pct_magz3_cosine_matrix_by_round.csv")

# Excel rows 2-41
data = df.iloc[0:40]

# Column B (rounds)
rounds = data.iloc[:, 1].tolist()

# Columns E:CZ
cosine_data = data.iloc[:, 4:104]

# Create empty DataFrames
cos_values = pd.DataFrame(index=cosine_data.index, columns=cosine_data.columns, dtype=float)
z_values = pd.DataFrame(index=cosine_data.index, columns=cosine_data.columns, dtype=float)

for col in cosine_data.columns:
    # Extract cosine values
    cos_values[col] = (
        cosine_data[col]
        .astype(str)
        .str.extract(r'cos=([-\d.]+)', expand=False)
        .astype(float)
    )

    # Extract z values
    z_values[col] = (
        cosine_data[col]
        .astype(str)
        .str.extract(r'z=([-\d.]+)', expand=False)
        .astype(float)
    )

In [8]:
print("\nCosine values:")
print(cos_values)

Cosine values:
    client_0  client_1  client_2  client_3  client_4  client_5  client_6  \
0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
1        NaN       NaN       NaN       NaN       NaN       NaN       NaN
2        NaN       NaN       NaN       NaN       NaN       NaN       NaN
3        NaN       NaN       NaN       NaN       NaN       NaN       NaN
4        NaN       NaN       NaN       NaN       NaN       NaN       NaN
5        NaN       NaN       NaN       NaN       NaN       NaN       NaN
6        NaN       NaN       NaN       NaN       NaN       NaN       NaN
7        NaN       NaN       NaN       NaN       NaN       NaN       NaN
8        NaN       NaN       NaN       NaN       NaN       NaN       NaN
9        NaN       NaN       NaN       NaN       NaN       NaN       NaN
10    0.7507       NaN       NaN       NaN       NaN       NaN    0.7529
11       NaN   -0.0038       NaN       NaN       NaN       NaN       NaN
12       NaN       NaN       NaN       NaN       NaN       NaN       NaN
13       NaN       NaN       NaN       NaN       NaN       NaN       NaN
14       NaN       NaN    0.0165    0.5198    0.5175       NaN       NaN
15       NaN       NaN       NaN       NaN       NaN       NaN       NaN
16       NaN       NaN       NaN       NaN       NaN       NaN       NaN
17       NaN       NaN       NaN       NaN       NaN       NaN       NaN
18       NaN       NaN       NaN       NaN       NaN       NaN       NaN
19       NaN       NaN       NaN       NaN       NaN    0.5796       NaN
20       NaN       NaN       NaN   -0.0091       NaN       NaN       NaN
21       NaN       NaN    0.5803       NaN       NaN       NaN       NaN
22       NaN       NaN       NaN       NaN       NaN       NaN       NaN
23       NaN       NaN       NaN       NaN       NaN       NaN       NaN
24       NaN       NaN       NaN       NaN       NaN       NaN       NaN
25       NaN       NaN       NaN       NaN       NaN       NaN       NaN
26   -0.0096       NaN       NaN       NaN       NaN   -0.0187       NaN
27       NaN    0.4658       NaN       NaN       NaN       NaN       NaN
28       NaN       NaN       NaN       NaN   -0.0051       NaN   -0.0029
29       NaN       NaN       NaN       NaN       NaN       NaN       NaN
30       NaN       NaN       NaN       NaN       NaN       NaN       NaN
31       NaN       NaN       NaN       NaN       NaN       NaN       NaN
32       NaN       NaN       NaN       NaN       NaN   -0.0139   -0.0047
33       NaN       NaN    0.8307       NaN       NaN       NaN       NaN
34       NaN       NaN       NaN       NaN   -0.0067       NaN       NaN
35       NaN       NaN       NaN       NaN       NaN       NaN       NaN
36   -0.0117       NaN       NaN   -0.0059       NaN       NaN       NaN
37       NaN       NaN       NaN       NaN       NaN       NaN       NaN
38       NaN       NaN       NaN       NaN       NaN       NaN       NaN
39       NaN   -0.0126       NaN       NaN       NaN       NaN       NaN

    client_7  client_8  client_9  ...  client_90  client_91  client_92  \
0        NaN       NaN       NaN  ...        NaN        NaN        NaN
1        NaN       NaN       NaN  ...        NaN        NaN        NaN
2        NaN       NaN       NaN  ...        NaN        NaN        NaN
3        NaN       NaN       NaN  ...        NaN        NaN        NaN
4        NaN       NaN       NaN  ...        NaN        NaN        NaN
5        NaN       NaN       NaN  ...        NaN        NaN        NaN
6        NaN       NaN       NaN  ...        NaN        NaN        NaN
7        NaN       NaN       NaN  ...        NaN        NaN        NaN
8        NaN       NaN       NaN  ...        NaN        NaN        NaN
9        NaN       NaN       NaN  ...        NaN        NaN        NaN
10       NaN       NaN       NaN  ...        NaN    -0.0003        NaN
11       NaN       NaN       NaN  ...        NaN        NaN        NaN
12    0.0080       NaN       NaN  ...        NaN        NaN        NaN
13       NaN       NaN       NaN  ...        NaN        NaN        NaN
14       NaN       NaN       NaN  ...        NaN        NaN        NaN
15       NaN       NaN       NaN  ...        NaN        NaN        NaN
16       NaN       NaN    0.0243  ...     0.7086        NaN        NaN
17       NaN       NaN       NaN  ...        NaN        NaN     0.0101
18       NaN    0.0087       NaN  ...        NaN        NaN        NaN
19       NaN       NaN       NaN  ...        NaN        NaN        NaN
20       NaN       NaN       NaN  ...        NaN        NaN        NaN
21       NaN       NaN       NaN  ...        NaN        NaN        NaN
22       NaN       NaN       NaN  ...        NaN        NaN        NaN
23       NaN       NaN       NaN  ...        NaN        NaN     0.7450
24       NaN       NaN       NaN  ...        NaN        NaN        NaN
25       NaN    0.2919       NaN  ...        NaN        NaN        NaN
26       NaN       NaN       NaN  ...        NaN        NaN        NaN
27       NaN       NaN    0.6790  ...        NaN        NaN        NaN
28       NaN       NaN       NaN  ...     0.0046        NaN        NaN
29       NaN       NaN       NaN  ...        NaN        NaN        NaN
30       NaN       NaN       NaN  ...        NaN        NaN        NaN
31    0.4263       NaN       NaN  ...        NaN     0.6519        NaN
32       NaN       NaN       NaN  ...        NaN        NaN        NaN
33       NaN       NaN       NaN  ...        NaN        NaN        NaN
34       NaN       NaN       NaN  ...        NaN        NaN        NaN
35    0.3342       NaN       NaN  ...        NaN        NaN     0.5640
36       NaN       NaN       NaN  ...        NaN        NaN        NaN
37       NaN       NaN       NaN  ...        NaN        NaN        NaN
38       NaN       NaN       NaN  ...        NaN        NaN        NaN
39       NaN    0.4752       NaN  ...        NaN        NaN        NaN

    client_93  client_94  client_95  client_96  client_97  client_98  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN
2         NaN        NaN        NaN        NaN        NaN        NaN
3         NaN        NaN        NaN        NaN        NaN        NaN
4         NaN        NaN        NaN        NaN        NaN        NaN
5         NaN        NaN        NaN        NaN        NaN        NaN
6         NaN        NaN        NaN        NaN        NaN        NaN
7         NaN        NaN        NaN        NaN        NaN        NaN
8         NaN        NaN        NaN        NaN        NaN        NaN
9         NaN        NaN        NaN        NaN        NaN        NaN
10        NaN        NaN        NaN        NaN        NaN        NaN
11        NaN        NaN     0.7283     0.0240        NaN        NaN
12        NaN        NaN        NaN        NaN        NaN        NaN
13        NaN        NaN        NaN        NaN        NaN        NaN
14        NaN        NaN        NaN        NaN        NaN        NaN
15        NaN        NaN        NaN        NaN     0.3931        NaN
16        NaN        NaN        NaN        NaN        NaN     0.0037
17        NaN     0.4130        NaN        NaN        NaN        NaN
18        NaN        NaN        NaN        NaN        NaN        NaN
19     0.5802        NaN        NaN        NaN        NaN        NaN
20        NaN        NaN    -0.0161        NaN        NaN        NaN
21        NaN        NaN        NaN        NaN        NaN        NaN
22        NaN        NaN        NaN        NaN        NaN        NaN
23        NaN        NaN        NaN        NaN        NaN        NaN
24        NaN    -0.0123        NaN        NaN        NaN        NaN
25        NaN        NaN        NaN        NaN        NaN        NaN
26        NaN        NaN        NaN        NaN    -0.0052        NaN
27        NaN        NaN        NaN     0.5109        NaN        NaN
28        NaN        NaN        NaN        NaN        NaN        NaN
29        NaN        NaN        NaN        NaN        NaN        NaN
30    -0.0171        NaN        NaN        NaN        NaN        NaN
31        NaN        NaN        NaN        NaN        NaN     0.2910
32        NaN        NaN        NaN        NaN    -0.0129        NaN
33        NaN        NaN        NaN     0.2872        NaN        NaN
34        NaN        NaN    -0.0052        NaN        NaN        NaN
35        NaN        NaN        NaN        NaN        NaN        NaN
36        NaN        NaN        NaN        NaN        NaN        NaN
37        NaN        NaN        NaN        NaN        NaN        NaN
38        NaN        NaN        NaN        NaN        NaN        NaN
39        NaN        NaN        NaN        NaN        NaN        NaN

    client_99
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17     0.0072
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29     0.4693
30        NaN
31        NaN
32        NaN
33        NaN
34        NaN
35     0.7682
36        NaN
37        NaN
38        NaN
39        NaN

[40 rows x 100 columns]

In [9]:
print("\nZ values:")
print(z_values)

Z values:
    client_0  client_1  client_2  client_3  client_4  client_5  client_6  \
0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
1        NaN       NaN       NaN       NaN       NaN       NaN       NaN
2        NaN       NaN       NaN       NaN       NaN       NaN       NaN
3        NaN       NaN       NaN       NaN       NaN       NaN       NaN
4        NaN       NaN       NaN       NaN       NaN       NaN       NaN
5        NaN       NaN       NaN       NaN       NaN       NaN       NaN
6        NaN       NaN       NaN       NaN       NaN       NaN       NaN
7        NaN       NaN       NaN       NaN       NaN       NaN       NaN
8        NaN       NaN       NaN       NaN       NaN       NaN       NaN
9        NaN       NaN       NaN       NaN       NaN       NaN       NaN
10   95.1764       NaN       NaN       NaN       NaN       NaN   94.9875
11       NaN    0.6554       NaN       NaN       NaN       NaN       NaN
12       NaN       NaN       NaN       NaN       NaN       NaN       NaN
13       NaN       NaN       NaN       NaN       NaN       NaN       NaN
14       NaN       NaN    0.0746   47.4764   47.3428       NaN       NaN
15       NaN       NaN       NaN       NaN       NaN       NaN       NaN
16       NaN       NaN       NaN       NaN       NaN       NaN       NaN
17       NaN       NaN       NaN       NaN       NaN       NaN       NaN
18       NaN       NaN       NaN       NaN       NaN       NaN       NaN
19       NaN       NaN       NaN       NaN       NaN   51.1606       NaN
20       NaN       NaN       NaN   41.2593       NaN       NaN       NaN
21       NaN       NaN    0.2995       NaN       NaN       NaN       NaN
22       NaN       NaN       NaN       NaN       NaN       NaN       NaN
23       NaN       NaN       NaN       NaN       NaN       NaN       NaN
24       NaN       NaN       NaN       NaN       NaN       NaN       NaN
25       NaN       NaN       NaN       NaN       NaN       NaN       NaN
26   52.5955       NaN       NaN       NaN       NaN   52.6317       NaN
27       NaN    0.4994       NaN       NaN       NaN       NaN       NaN
28       NaN       NaN       NaN       NaN   53.4754       NaN   53.3823
29       NaN       NaN       NaN       NaN       NaN       NaN       NaN
30       NaN       NaN       NaN       NaN       NaN       NaN       NaN
31       NaN       NaN       NaN       NaN       NaN       NaN       NaN
32       NaN       NaN       NaN       NaN       NaN   49.8432   49.7263
33       NaN       NaN    0.3484       NaN       NaN       NaN       NaN
34       NaN       NaN       NaN       NaN   55.5808       NaN       NaN
35       NaN       NaN       NaN       NaN       NaN       NaN       NaN
36   48.8615       NaN       NaN   48.9016       NaN       NaN       NaN
37       NaN       NaN       NaN       NaN       NaN       NaN       NaN
38       NaN       NaN       NaN       NaN       NaN       NaN       NaN
39       NaN    0.8276       NaN       NaN       NaN       NaN       NaN

    client_7  client_8  client_9  ...  client_90  client_91  client_92  \
0        NaN       NaN       NaN  ...        NaN        NaN        NaN
1        NaN       NaN       NaN  ...        NaN        NaN        NaN
2        NaN       NaN       NaN  ...        NaN        NaN        NaN
3        NaN       NaN       NaN  ...        NaN        NaN        NaN
4        NaN       NaN       NaN  ...        NaN        NaN        NaN
5        NaN       NaN       NaN  ...        NaN        NaN        NaN
6        NaN       NaN       NaN  ...        NaN        NaN        NaN
7        NaN       NaN       NaN  ...        NaN        NaN        NaN
8        NaN       NaN       NaN  ...        NaN        NaN        NaN
9        NaN       NaN       NaN  ...        NaN        NaN        NaN
10       NaN       NaN       NaN  ...        NaN     0.1322        NaN
11       NaN       NaN       NaN  ...        NaN        NaN        NaN
12    0.4435       NaN       NaN  ...        NaN        NaN        NaN
13       NaN       NaN       NaN  ...        NaN        NaN        NaN
14       NaN       NaN       NaN  ...        NaN        NaN        NaN
15       NaN       NaN       NaN  ...        NaN        NaN        NaN
16       NaN       NaN    0.2763  ...    44.3675        NaN        NaN
17       NaN       NaN       NaN  ...        NaN        NaN     0.0265
18       NaN    0.1304       NaN  ...        NaN        NaN        NaN
19       NaN       NaN       NaN  ...        NaN        NaN        NaN
20       NaN       NaN       NaN  ...        NaN        NaN        NaN
21       NaN       NaN       NaN  ...        NaN        NaN        NaN
22       NaN       NaN       NaN  ...        NaN        NaN        NaN
23       NaN       NaN       NaN  ...        NaN        NaN     0.2212
24       NaN       NaN       NaN  ...        NaN        NaN        NaN
25       NaN    0.1706       NaN  ...        NaN        NaN        NaN
26       NaN       NaN       NaN  ...        NaN        NaN        NaN
27       NaN       NaN    0.1441  ...        NaN        NaN        NaN
28       NaN       NaN       NaN  ...    53.2901        NaN        NaN
29       NaN       NaN       NaN  ...        NaN        NaN        NaN
30       NaN       NaN       NaN  ...        NaN        NaN        NaN
31    0.2937       NaN       NaN  ...        NaN     0.0048        NaN
32       NaN       NaN       NaN  ...        NaN        NaN        NaN
33       NaN       NaN       NaN  ...        NaN        NaN        NaN
34       NaN       NaN       NaN  ...        NaN        NaN        NaN
35    0.3023       NaN       NaN  ...        NaN        NaN     0.1861
36       NaN       NaN       NaN  ...        NaN        NaN        NaN
37       NaN       NaN       NaN  ...        NaN        NaN        NaN
38       NaN       NaN       NaN  ...        NaN        NaN        NaN
39       NaN    0.0373       NaN  ...        NaN        NaN        NaN

    client_93  client_94  client_95  client_96  client_97  client_98  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN
2         NaN        NaN        NaN        NaN        NaN        NaN
3         NaN        NaN        NaN        NaN        NaN        NaN
4         NaN        NaN        NaN        NaN        NaN        NaN
5         NaN        NaN        NaN        NaN        NaN        NaN
6         NaN        NaN        NaN        NaN        NaN        NaN
7         NaN        NaN        NaN        NaN        NaN        NaN
8         NaN        NaN        NaN        NaN        NaN        NaN
9         NaN        NaN        NaN        NaN        NaN        NaN
10        NaN        NaN        NaN        NaN        NaN        NaN
11        NaN        NaN    74.5612     0.0386        NaN        NaN
12        NaN        NaN        NaN        NaN        NaN        NaN
13        NaN        NaN        NaN        NaN        NaN        NaN
14        NaN        NaN        NaN        NaN        NaN        NaN
15        NaN        NaN        NaN        NaN    41.8768        NaN
16        NaN        NaN        NaN        NaN        NaN     0.0662
17        NaN    47.2395        NaN        NaN        NaN        NaN
18        NaN        NaN        NaN        NaN        NaN        NaN
19    51.2007        NaN        NaN        NaN        NaN        NaN
20        NaN        NaN    41.3539        NaN        NaN        NaN
21        NaN        NaN        NaN        NaN        NaN        NaN
22        NaN        NaN        NaN        NaN        NaN        NaN
23        NaN        NaN        NaN        NaN        NaN        NaN
24        NaN    47.1392        NaN        NaN        NaN        NaN
25        NaN        NaN        NaN        NaN        NaN        NaN
26        NaN        NaN        NaN        NaN    52.6386        NaN
27        NaN        NaN        NaN     0.0036        NaN        NaN
28        NaN        NaN        NaN        NaN        NaN        NaN
29        NaN        NaN        NaN        NaN        NaN        NaN
30    48.3928        NaN        NaN        NaN        NaN        NaN
31        NaN        NaN        NaN        NaN        NaN     0.6390
32        NaN        NaN        NaN        NaN    49.8253        NaN
33        NaN        NaN        NaN     0.2544        NaN        NaN
34        NaN        NaN    55.5447        NaN        NaN        NaN
35        NaN        NaN        NaN        NaN        NaN        NaN
36        NaN        NaN        NaN        NaN        NaN        NaN
37        NaN        NaN        NaN        NaN        NaN        NaN
38        NaN        NaN        NaN        NaN        NaN        NaN
39        NaN        NaN        NaN        NaN        NaN        NaN

    client_99
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17     0.1158
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29     0.0134
30        NaN
31        NaN
32        NaN
33        NaN
34        NaN
35     0.2831
36        NaN
37        NaN
38        NaN
39        NaN

[40 rows x 100 columns]

In [10]:
df = z_values
df

,client_0,client_1,client_2,client_3,client_4,client_5,client_6,client_7,client_8,client_9,...,client_90,client_91,client_92,client_93,client_94,client_95,client_96,client_97,client_98,client_99
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,95.1764,NaN,NaN,NaN,NaN,NaN,94.9875,NaN,NaN,NaN,...,NaN,0.1322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,0.6554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,74.5612,0.0386,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4435,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,0.0746,47.4764,47.3428,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.8768,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2763,...,44.3675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0662,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0265,NaN,47.2395,NaN,NaN,NaN,NaN,0.1158
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1304,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,51.1606,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,51.2007,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,41.2593,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41.3539,NaN,NaN,NaN,NaN
21,NaN,NaN,0.2995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.2212,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,47.1392,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1706,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,52.5955,NaN,NaN,NaN,NaN,52.6317,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.6386,NaN,NaN
27,NaN,0.4994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.1441,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0036,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,53.4754,NaN,53.3823,NaN,NaN,NaN,...,53.2901,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0134
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,48.3928,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2937,NaN,NaN,...,NaN,0.0048,NaN,NaN,NaN,NaN,NaN,NaN,0.6390,NaN
32,NaN,NaN,NaN,NaN,NaN,49.8432,49.7263,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.8253,NaN,NaN
33,NaN,NaN,0.3484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.2544,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,55.5808,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,55.5447,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.3023,NaN,NaN,...,NaN,NaN,0.1861,NaN,NaN,NaN,NaN,NaN,NaN,0.2831
36,48.8615,NaN,NaN,48.9016,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,0.8276,NaN,NaN,NaN,NaN,NaN,NaN,0.0373,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
good = [[] for _ in range(len(z_values))]
bad = [[] for _ in range(len(z_values))]

for row_idx, row in z_values.iterrows():
    for col_name, value in row.items():
        if pd.notna(value):
            #print(col_name, value)
            client = col_name.replace("client_", "")
            client = int(client)
            if client in fr2_list:
                bad[row_idx].append(value)
            else:
                good[row_idx].append(value)

In [40]:
good_z = pd.DataFrame(good)
good_z

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.6870,0.4105,0.6708,0.1322,NaN,NaN,NaN,NaN,NaN,NaN
11,0.6554,0.4038,0.2567,0.3074,0.0000,0.1661,0.0386,NaN,NaN,NaN
12,0.4435,0.8078,0.2816,0.4176,0.9196,0.1435,0.1497,0.3275,NaN,NaN
13,1.1384,0.1544,0.8285,0.1342,0.6868,NaN,NaN,NaN,NaN,NaN
14,0.0746,0.4852,0.4180,0.6937,0.1568,0.3084,NaN,NaN,NaN,NaN
15,0.4145,0.5805,0.5222,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0.2763,0.5060,0.6638,0.4722,0.1083,0.2847,0.3795,0.0662,NaN,NaN
17,0.4005,0.2447,0.0265,0.1158,NaN,NaN,NaN,NaN,NaN,NaN
18,0.1304,0.1765,0.6744,0.2332,0.5962,0.4094,0.2146,0.2429,NaN,NaN
19,0.0675,0.7215,0.7081,0.2630,0.2573,0.6446,0.0611,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,0.2995,0.6328,0.5038,0.8878,0.1008,0.5963,0.0220,0.6020,0.0902,0.2691
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,0.8531,0.5392,0.3730,0.2144,0.7554,0.2718,0.6970,0.2768,0.3302,0.2212
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,0.1706,0.0373,0.2134,0.8136,0.1699,0.7650,0.0221,0.4790,0.3462,0.6745
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,0.4994,0.1441,0.9396,0.6347,0.7488,0.5036,0.2810,0.2109,0.4712,0.0036
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0.1912,0.6657,0.5751,0.6848,0.5315,0.5557,0.6711,0.9947,0.8403,0.0134
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.2937,0.2821,0.2911,0.5059,0.6939,0.5128,0.4027,0.1373,0.0048,0.6390
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,0.3484,0.2373,0.7758,0.1776,0.3808,0.8328,0.5608,0.4218,0.6216,0.2544
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,0.3023,0.4657,0.3255,0.6198,0.4555,0.5680,0.3581,0.1755,0.1861,0.2831
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0.5026,0.5710,1.1147,0.5270,0.6905,0.0629,0.3620,0.4828,0.0793,0.6705
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,0.8276,0.0373,0.6770,0.2070,0.0998,0.1643,0.2647,0.8493,0.2499,0.3644

In [41]:
bad_z = pd.DataFrame(bad)
bad_z

          0        1        2        3        4        5        6
0       NaN      NaN      NaN      NaN      NaN      NaN      NaN
1       NaN      NaN      NaN      NaN      NaN      NaN      NaN
2       NaN      NaN      NaN      NaN      NaN      NaN      NaN
3       NaN      NaN      NaN      NaN      NaN      NaN      NaN
4       NaN      NaN      NaN      NaN      NaN      NaN      NaN
5       NaN      NaN      NaN      NaN      NaN      NaN      NaN
6       NaN      NaN      NaN      NaN      NaN      NaN      NaN
7       NaN      NaN      NaN      NaN      NaN      NaN      NaN
8       NaN      NaN      NaN      NaN      NaN      NaN      NaN
9       NaN      NaN      NaN      NaN      NaN      NaN      NaN
10  95.1764  94.9875  95.2392  94.5019  94.8654  95.7054      NaN
11  74.5569  74.3214  74.5612      NaN      NaN      NaN      NaN
12  61.6044  61.8022      NaN      NaN      NaN      NaN      NaN
13  47.9338  47.8426  47.9000  47.9239  47.8681      NaN      NaN
14  47.4764  47.3428  47.6202  47.3556      NaN      NaN      NaN
15  41.8747  41.7961  41.8385  41.9262  41.9336  41.9700  41.8768
16  44.4479  44.3675      NaN      NaN      NaN      NaN      NaN
17  47.2549  47.3688  47.3117  47.1858  47.2259  47.2395      NaN
18  59.8410  60.0660      NaN      NaN      NaN      NaN      NaN
19  51.1606  51.3783  51.2007      NaN      NaN      NaN      NaN
20  41.2593  41.2257  41.2451  41.2666  41.2455  41.2633  41.3539
21      NaN      NaN      NaN      NaN      NaN      NaN      NaN
22  55.8382  55.8076  55.8993  55.5856  55.8518  55.7566  55.6987
23      NaN      NaN      NaN      NaN      NaN      NaN      NaN
24  47.1155  46.9516  47.0481  47.1033  47.1506  47.1585  47.1392
25      NaN      NaN      NaN      NaN      NaN      NaN      NaN
26  52.5955  52.6317  52.6281  52.6271  52.5482  52.5340  52.6386
27      NaN      NaN      NaN      NaN      NaN      NaN      NaN
28  53.4754  53.3823  53.1982  53.3027  53.2440  53.2449  53.2901
29      NaN      NaN      NaN      NaN      NaN      NaN      NaN
30  48.5066  48.4643  48.4455  48.3339  48.3928      NaN      NaN
31      NaN      NaN      NaN      NaN      NaN      NaN      NaN
32  49.8432  49.7263  49.8943  49.8666  49.8438  49.9194  49.8253
33      NaN      NaN      NaN      NaN      NaN      NaN      NaN
34  55.5808  55.7425  55.5103  55.5212  55.7035  55.6286  55.5447
35      NaN      NaN      NaN      NaN      NaN      NaN      NaN
36  48.8615  48.9016  48.8535  48.8018  48.8731  48.9002  48.9698
37      NaN      NaN      NaN      NaN      NaN      NaN      NaN
38  50.0615  50.1109  49.9878  50.1976  50.0642  50.2025  50.2714
39      NaN      NaN      NaN      NaN      NaN      NaN      NaN

In [42]:
import pandas as pd

bad_z = pd.DataFrame(bad)
good_z = pd.DataFrame(good)

# Per row statistics
summary = pd.DataFrame({
    "good_low": good_z.min(axis=1),
    "good_high": good_z.max(axis=1),
    "good_avg": good_z.mean(axis=1),

    "bad_low": bad_z.min(axis=1),
    "bad_high": bad_z.max(axis=1),
    "bad_avg": bad_z.mean(axis=1)
})

print(summary)

    good_low  good_high  good_avg  bad_low  bad_high    bad_avg
0        NaN        NaN       NaN      NaN       NaN        NaN
1        NaN        NaN       NaN      NaN       NaN        NaN
2        NaN        NaN       NaN      NaN       NaN        NaN
3        NaN        NaN       NaN      NaN       NaN        NaN
4        NaN        NaN       NaN      NaN       NaN        NaN
5        NaN        NaN       NaN      NaN       NaN        NaN
6        NaN        NaN       NaN      NaN       NaN        NaN
7        NaN        NaN       NaN      NaN       NaN        NaN
8        NaN        NaN       NaN      NaN       NaN        NaN
9        NaN        NaN       NaN      NaN       NaN        NaN
10    0.1322     0.6870  0.475125  94.5019   95.7054  95.079300
11    0.0000     0.6554  0.261143  74.3214   74.5612  74.479833
12    0.1435     0.9196  0.436350  61.6044   61.8022  61.703300
13    0.1342     1.1384  0.588460  47.8426   47.9338  47.893680
14    0.0746     0.6937  0.356117  47.3428   47.6202  47.448750
15    0.4145     0.5805  0.505733  41.7961   41.9700  41.887986
16    0.0662     0.6638  0.344625  44.3675   44.4479  44.407700
17    0.0265     0.4005  0.196875  47.1858   47.3688  47.264433
18    0.1304     0.6744  0.334700  59.8410   60.0660  59.953500
19    0.0611     0.7215  0.389014  51.1606   51.3783  51.246533
20       NaN        NaN       NaN  41.2257   41.3539  41.265629
21    0.0220     0.8878  0.400430      NaN       NaN        NaN
22       NaN        NaN       NaN  55.5856   55.8993  55.776829
23    0.2144     0.8531  0.453210      NaN       NaN        NaN
24       NaN        NaN       NaN  46.9516   47.1585  47.095257
25    0.0221     0.8136  0.369160      NaN       NaN        NaN
26       NaN        NaN       NaN  52.5340   52.6386  52.600457
27    0.0036     0.9396  0.443690      NaN       NaN        NaN
28       NaN        NaN       NaN  53.1982   53.4754  53.305371
29    0.0134     0.9947  0.572350      NaN       NaN        NaN
30       NaN        NaN       NaN  48.3339   48.5066  48.428620
31    0.0048     0.6939  0.376330      NaN       NaN        NaN
32       NaN        NaN       NaN  49.7263   49.9194  49.845557
33    0.1776     0.8328  0.461130      NaN       NaN        NaN
34       NaN        NaN       NaN  55.5103   55.7425  55.604514
35    0.1755     0.6198  0.373960      NaN       NaN        NaN
36       NaN        NaN       NaN  48.8018   48.9698  48.880214
37    0.0629     1.1147  0.506330      NaN       NaN        NaN
38       NaN        NaN       NaN  49.9878   50.2714  50.127986
39    0.0373     0.8493  0.374130      NaN       NaN        NaN